# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20160728_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amc_8_locks',
            field=models.CharField(default='False;False;False;False;False', max_length=100),
            preserve_default=False,
        ),
    ]
