# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_amc_8_locks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amc_10_locks',
            field=models.CharField(default='False;False;False;False;False', max_length=100),
            preserve_default=False,
        ),
    ]
