# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_amc_10_locks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='saved_answers',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
