# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20160801_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='num_tries',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='saved_answers',
            field=models.CharField(max_length=1000),
        ),
    ]
