# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-18 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20161217_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='amc_10_locks',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='amc_10_scores',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='amc_8_locks',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='amc_8_scores',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='usaco_bronze_locks',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='usaco_bronze_scores',
            field=models.CharField(max_length=500),
        ),
    ]
